# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    image: mysql:5.7 #original_mysql_world # イメージの名前
    environment:
        MYSQL_DATABASE: flask_sv
        MYSQL_USER: creist
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    ports:
    - 3306:3306
